name: Run Packer Build

on:
  push:
    branches: [ main ]
    
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: hashicorp/packer-github-actions@v0.2.0
      - name: Packer GitHub Actions
        with:
          command: init
          arguments: "-var-file=windows11-vars.pkvars.hcl"
          target: /windows/.
