name: Packer

on:
  push:

jobs:
  Build-Machine:
    runs-on: ubuntu-latest
    name: Build Windows Image

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Validate template
      - name: Validate Template
        uses: hashicorp/packer-github-actions@master
        with:
          command: validate
          arguments: "-var-file=windows11-vars.pkvars.hcl -syntax-only"
          target: .
          
      # Initialize Build template
      - name: Validate Template
        uses: hashicorp/packer-github-actions@master
        with:
          command: init
          arguments: "-var-file=windows11-vars.pkvars.hcl -syntax-only"
          target: .

      # Build artifact
      - name: Build Artifact
        uses: hashicorp/packer-github-actions@master
        with:
          command: build
          arguments: "-var-file=windows11-vars.pkvars.hcl"
          target: .
