name: Packer

on: workflow_dispatch

jobs:
  Build-Machine:
    runs-on: ubuntu-latest
    name: Build Windows Image

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Validate template
      - name: Validate Build
        uses: hashicorp/packer-github-actions@master
        with:
          command: validate
          arguments: "-var-file=windows11-vars.pkvars.hcl -syntax-only"
          target: .
          
      # Initialize Build template
      - name: Initialize Plugins
        uses: hashicorp/packer-github-actions@master
        with:
          command: init
          arguments: "-var-file=windows11-vars.pkvars.hcl"
          target: .

      # Build artifact
      - name: Build Artifact
        uses: hashicorp/packer-github-actions@master
        with:
          command: build
          arguments: "-var-file=windows11-vars.pkvars.hcl"
          target: .
        env:
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          SUBSCRIPTION_ID: ${{ secrets.SUBSCRIPTION_ID }}
